//#### 1. `js/data2-karty.js`
//Ten plik będzie przechowywał wszystkie Twoje dane kart.

// js/data2-karty.js

const sampleData = {
pola_planszy: [
{ value: "00", label: "00 😓 Kraina ofiar" },
{ value: "01", label: "A01 🕸️🕷️ Przekonanie" },
{ value: "02", label: "A02 🔒🫀 Blokada energii" },
{ value: "03", label: "A03 📽️ Projekcja" },
{ value: "04", label: "A04 👉🏻🙎🏻‍♂️ Zabawa w obwinianie" },
{ value: "05", label: "A05 🕸️🕷️ Przekonanie" },
{ value: "06", label: "A06 🔒🫀 Blokada energii" },
{ value: "07", label: "A07 📽️ Projekcja" },
{ value: "08", label: "A08 ☯️ KARMA" },
{ value: "09", label: "A09 🕸️🕷️ Przekonanie" },
{ value: "10", label: "A10 🔒🫀 Blokada energii" },
{ value: "11", label: "A11 🤔💭 Wyobraź sobie!" },
{ value: "12", label: "A12 👉🏻🙎🏻‍♂️ Zabawa w obwinianie" },
{ value: "13", label: "A13 🕸️🕷️ Przekonanie" },
{ value: "14", label: "A14 ☯️ KARMA" },
{ value: "15", label: "A15 🤔💭 Wyobraź sobie!" },
{ value: "16", label: "=A16 ⛔ Wrota Świadomości STOP!" },
{ value: "17", label: "B17 💡 Światło" },
{ value: "18", label: "B18 🙋🏻‍♂️ Gotowość" },
{ value: "19", label: "B19 🤗 Samo- akceptacja" },
{ value: "20", label: "B20 💡 Światło" },
{ value: "21", label: "B21 😮‍💨 Westchnienie ulgi" },
{ value: "22", label: "B22 😅 Widzisz u innych własne cechy" },
{ value: "23", label: "B23 🙋🏻‍♂️ Gotowość" },
{ value: "24", label: "B24 🤗 Samo- akceptacja" },
{ value: "25", label: "B25 🤔💭 Wyobraź sobie!" },
{ value: "26", label: "B26 💡 Światło" },
{ value: "27", label: "B27 🙋🏻‍♂️ Gotowość" },
{ value: "28", label: "B28 🚫💔 Duchowy unik" },
{ value: "29", label: "B29 💡 Światło" },
{ value: "30", label: "B30 🔥 Pozbądź się tego" },
{ value: "31", label: "=B31 ⛔↪️ Wrota Przemiany STOP!" },
{ value: "32", label: "C32 😮‍💨 Westchnienie ulgi" },
{ value: "33", label: "C33 📖 Nowa opowieść" },
{ value: "34", label: "C34 💡 Światło" },
{ value: "35", label: "C35 👼🏻 Uzdrawiający Anioł" },
{ value: "36", label: "C36 🤔💭 Wyobraź sobie!" },
{ value: "37", label: "C37 🔥 Pozbądź się tego" },
{ value: "38", label: "C38 📖 Nowa opowieść" },
{ value: "39", label: "C39 💡 Światło" },
{ value: "40", label: "C40 👼🏻 Uzdrawiający Anioł" },
{ value: "41", label: "C41 ⚡ Moc" },
{ value: "42", label: "C42 📖 Nowa opowieść" },
{ value: "43", label: "C43 😮‍💨 Westchnienie ulgi" },
{ value: "44", label: "C44 💡 Światło" },
{ value: "45", label: "C45 📖 Nowa opowieść" },
{ value: "46", label: "=C46 ⛔ Wrota Poddania się STOP!" },
{ value: "47", label: "D47 😮‍💨 Westchnienie ulgi" },
{ value: "48", label: "D48 🔥 Pozbądź się tego" },
{ value: "49", label: "D49 💞 Radykalne Wybaczenie" },
{ value: "50", label: "D50 🥹 Poddanie się" },
{ value: "51", label: "D51 🤗 Samo- akceptacja" },
{ value: "52", label: "D52 🚫💔 Duchowy unik" },
{ value: "53", label: "D53 🤔💭 Wyobraź sobie!" },
{ value: "54", label: "D54 🔥 Pozbądź się tego" },
{ value: "55", label: "D55 ⚡ Moc" },
{ value: "56", label: "D56 💞 Radykalne Wybaczenie" },
{ value: "57", label: "D57 👼🏻 Uzdrawiający Anioł" },
{ value: "58", label: "D58 🌍 Jedność" },
{ value: "59", label: "D59 🤗 Samo- akceptacja" },
{ value: "60", label: "D60 🥹 Poddanie się" },
{ value: "61", label: "=D61 🧘🏻‍♂️ SATORI" }
],

pola_zdarzenie: [
  { value: "z001", label: "z001 Byłeś prześladowany za swe religijne/ duchowe przekonania." },
  { value: "z002", label: "z002 Doświadczyłeś nieuzasadnionej dyskryminacji." },
  { value: "z003", label: "z003 Działałeś wbrew własnym interesom." },
  { value: "z004", label: "z004 Ktoś boleśnie Cię odrzucił lub porzucił." },
  { value: "z005", label: "z005 Ktoś Cię okłamał bardzo perfidnie." },
  { value: "z006", label: "z006 Ktoś Cię zdradził bardzo boleśnie." },
  { value: "z007", label: "z007 Ktoś kogo kochałeś zmarł nieoczekiwanie." },
  { value: "z008", label: "z008 Ktoś odebrał Ci władzę." },
  { value: "z009", label: "z009 Ktoś skradł Twoje marzenia lub Ty uczyniłeś to komuś." },
  { value: "z010", label: "z010 Ktoś sprawił, że uległeś poważnemu wypadkowi." },
  { value: "z011", label: "z011 Ktoś uwiódł Twojego małżonka/ partnera." },
  { value: "z012", label: "z012 Musiałeś podjąć decyzję w sprawie niechcianej ciąży." },
  { value: "z013", label: "z013 Musiałeś zmierzyć się ze skutkami alkoholizmu/ narkomanii." },
  { value: "z014", label: "z014 Obwiniałeś się o coś, czemu nie zawiniłeś." },
  { value: "z015", label: "z015 Powiedziano Ci, że byłeś niechciany." },
  { value: "z016", label: "z016 Pozbawiono Cię kontaktu z Twoimi dziećmi." },
  { value: "z017", label: "z017 Rozmieniłeś się na drobne (zajmując się błahostkami zamiast czymś ważnym)." },
  { value: "z018", label: "z018 Uczyniono z Ciebie kozła ofiarnego." },
  { value: "z019", label: "z019 Utraciłeś miłość swego życia." },
  { value: "z020", label: "z020 Zostałeś dotknięty chorobą lub ranny." },
  { value: "z021", label: "z021 Zostałeś fizycznie/ emocjonalnie/ psychicznie zraniony." },
  { value: "z022", label: "z022 Zostałeś okropnie zawstydzony." },
  { value: "z023", label: "z023 Zostałeś oszukany bardzo perfidnie." },
  { value: "z024", label: "z024 Zostałeś surowo osądzony lub niesłusznie oskarżony." }
],

pola_kontekst: [
  { value: "k001", label: "k001 Cel życia." },
  { value: "k002", label: "k002 Ciało." },
  { value: "k003", label: "k003 Dług." },
  { value: "k004", label: "k004 Dzieci." },
  { value: "k005", label: "k005 Kariera." },
  { value: "k006", label: "k006 Kościół/ Instytucja religijna." },
  { value: "k007", label: "k007 Krewni." },
  { value: "k008", label: "k008 Małżeństwo/ Partner przyszły lub przeszły." },
  { value: "k009", label: "k009 Marzenia." },
  { value: "k010", label: "k010 Pieniądze." },
  { value: "k011", label: "k011 Praca/ Miejsce pracy." },
  { value: "k012", label: "k012 Prasa/ Media." },
  { value: "k013", label: "k013 Przyjaciele/ Grupa społeczna." },
  { value: "k014", label: "k014 Rodzina." },
  { value: "k015", label: "k015 Rząd." },
  { value: "k016", label: "k016 Seks." },
  { value: "k017", label: "k017 Społeczeństwo." },
  { value: "k018", label: "k018 Szkoła." },
  { value: "k019", label: "k019 Szpital lub Sanatorium." },
  { value: "k020", label: "k020 Tajemnice." },
  { value: "k021", label: "k021 Twórczość." },
  { value: "k022", label: "k022 Wakacje." },
  { value: "k023", label: "k023 Władza." },
  { value: "k024", label: "k024 Związki." }
],

karma: [
  { value: "ka001", label: "ka001 Bezstronność." },
  { value: "ka002", label: "ka002 Bogactwo." },
  { value: "ka003", label: "ka003 Bycie ignorowanym." },
  { value: "ka004", label: "ka004 Cierpienie." },
  { value: "ka005", label: "ka005 Dbałość." },
  { value: "ka006", label: "ka006 Intymność." },
  { value: "ka007", label: "ka007 Moja cielesność." },
  { value: "ka008", label: "ka008 Poczucie godności." },
  { value: "ka009", label: "ka009 Poczucie własnej wartości." },
  { value: "ka010", label: "ka010 Poddanie się." },
  { value: "ka011", label: "ka011 Pokój." },
  { value: "ka012", label: "ka012 Poniżenie." },
  { value: "ka013", label: "ka013 Porzucenie." },
  { value: "ka014", label: "ka014 Pozbywanie się uprzedzeń." },
  { value: "ka015", label: "ka015 Przebaczenie." },
  { value: "ka016", label: "ka016 Rodzina." },
  { value: "ka017", label: "ka017 Samoakceptacja." },
  { value: "ka018", label: "ka018 Seksualność." },
  { value: "ka019", label: "ka019 Sprawiedliwość." },
  { value: "ka020", label: "ka020 Tolerancja." },
  { value: "ka021", label: "ka021 Tożsamość płciowa." },
  { value: "ka022", label: "ka022 Wstyd." },
  { value: "ka023", label: "ka023 Zasługiwanie." },
  { value: "ka024", label: "ka024 Zdrada." }
],

wyobraz_sobie: [
  "wyobraźSobie: 01 Bierzesz sprawy w swoje ręce i sam kierujesz swoim życiem. Pozbądź się Przekonania [p30] lub Blokady Energii [p21].",
  "wyobraźSobie: 02 Brałeś wszystko zanadto do siebie. Poznaj Przekonanie.",
  "wyobraźSobie: 03 Byłeś posłuszny swej intuicji. Następne Wrota.",
  "wyobraźSobie: 04 Choroba sprawia że zwalniasz tempo. Przerwa.",
  "wyobraźSobie: 05 Czujesz się zagubiony. Odczytaj nowe Przekonanie.",
  "wyobraźSobie: 06 Czujesz, że życie jest ekscytujące. Rzuć kostką jeszcze raz.",
  "wyobraźSobie: 07 Działałeś na własną szkodę. Weź nowe Wydarzenie i Kontekst.",
  "wyobraźSobie: 08 Jesteś w depresji. Odkryj Blokadę Energii.",
  "wyobraźSobie: 09 Obudziła się w tobie zazdrość. Poznaj Przekonanie.",
  "wyobraźSobie: 10 Odzyskałeś wiarę w ludzkość. Uzdrawiający anioł [p35].",
  "wyobraźSobie: 11 Jesteś w świetnym nastroju. Moc [p41]...",
  "wyobraźSobie: 12 Podjąłeś ryzyko i rezultat okazał się wspaniały. Przesuń się do przodu o jedno pole.",
  "wyobraźSobie: 13 Pomyliłeś się. Cofnij się o jedno pole...",
  "wyobraźSobie: 14 Przegapiłeś okazję. Cofnij się o dwa pola...",
  "wyobraźSobie: 15 Robisz się coraz silniejszy. Przesuń się do przodu o 3 pola.",
  "wyobraźSobie: 16 Słońce wyziera zza chmur. Radykalne Wybaczenie [p49]...",
  "wyobraźSobie: 17 Twoja ocena była słuszna. Idź dwa pola do przodu.",
  "wyobraźSobie: 18 Twoje uczucia zostały zranione. Cofnij się o trzy pola.",
  "wyobraźSobie: 19 Twoje pozytywne myślenie przynosi dobre rezultaty. Weź Nową Opowieść [p33].",
  "wyobraźSobie: 20 Twój gniew eksploduje! Wyraź emocje. (Zabawa w obwinianie [p04])",
  "wyobraźSobie: 21 Widzisz u innych własne cechy [p22]. Weź Przekonanie lub Blokadę Energii.",
  "wyobraźSobie: 22 Zachowałeś się nieuczciwie. Poziom niżej. (minus 16 pól)",
  "wyobraźSobie: 23 Znalazłeś twórcze rozwiązanie problemu. Pozbądź się Przekonania [p30] i Blokady Energii [p21].",
  "wyobraźSobie: 24 Zwycięstwo jest nieuniknione. Następne Wrota."
],


przekonanie: [
 "przekonanie: 001. Aby być kochanym, muszę być kimś innym niż jestem.",
 "przekonanie: 002. Boję się nawiązywania bliskich relacji.",
 "przekonanie: 003. Boję się osiągnąć sukces.",
 "przekonanie: 004. Chyba nie dam rady.",
 "przekonanie: 005. Coś mi przeszkadza w osiągnięciu mego celu.",
 "przekonanie: 006. Coś musi być ze mną nie w porządku.",
 "przekonanie: 007. Ja się nie liczę - inni są ważniejsi ode mnie.",
 "przekonanie: 008. Jestem zbyt schorowany i słaby.",
 "przekonanie: 009. Jestem zupełnie sam na świecie.",
 "przekonanie: 010. Jeśli będę narzekać, narobię sobie kłopotów.",
 "przekonanie: 011. Jeśli otworzę swe serce, zostanę zraniony.",
 "przekonanie: 012. Jeśli pokażę prawdziwą twarz, nikt nie będzie mnie kochać.",
 "przekonanie: 013. Moje życie po prostu się nie układa.",
 "przekonanie: 014. Muszę być doskonały, aby mnie kochano.",
 "przekonanie: 015. Muszę mieć nad wszystkim kontrolę.",
 "przekonanie: 016. Na wszystko muszę ciężko zapracować.",
 "przekonanie: 017. Nie jestem wart miłości.",
 "przekonanie: 018. Nie jestem zbyt lubiany.",
 "przekonanie: 019. Nie mam żadnych uzdolnień.",
 "przekonanie: 020. Nie mogę sobie ufać.",
 "przekonanie: 021. Nie staję na wysokości zadania.",
 "przekonanie: 022. Nie wyglądam dobrze i tyle.",
 "przekonanie: 023. Nie zasługuję na miłość.",
 "przekonanie: 024. Nie zasługuję na pieniądze.",
 "przekonanie: 025. Nie zasługuję na szczęście.",
 "przekonanie: 026. Nie zasługuję na to, aby być rodzicem.",
 "przekonanie: 027. Nie zasługuję, aby mieć to, czego pragnę.",
 "przekonanie: 028. Nigdy nic mi się nie udaje!",
 "przekonanie: 029. Nigdy nie będę dość dobry.",
 "przekonanie: 030. Nigdy nie będę mieć dość pieniędzy.",
 "przekonanie: 031. Nigdy nie dorastam do sytuacji.",
 "przekonanie: 032. Nigdzie nie pasuję.",
 "przekonanie: 033. Nikomu nie mogę ufać.",
 "przekonanie: 034. Obawiam się bliskości.",
 "przekonanie: 035. Sam naprawdę nie dam sobie rady.",
 "przekonanie: 036. Trudno mnie kochać takim jakim jestem.",
 "przekonanie: 037. Wciąż przydarza mi się coś złego.",
 "przekonanie: 038. Wszyscy ciągle mi dokuczają.",
 "przekonanie: 039. Wszyscy mnie ciągle osądzają.",
 "przekonanie: 040. Wszyscy mnie ignorują i nie zwracają na mnie uwagi.",
 "przekonanie: 041. Zapewne mi się nie uda.",
 "przekonanie: 042. Zawsze będę sam.",
 "przekonanie: 043. Zawsze czegoś brakuje.",
 "przekonanie: 044. Zawsze wszystko robię źle.",
 "przekonanie: 045. Złe rzeczy zawsze przydarzają się dobrym ludziom.",
 "przekonanie: 046. Życie jest niebezpieczne i okrutne.",
 "przekonanie: 047. Życie jest przygnębiające.",
 "przekonanie: 048. Życie jest walką, a to co najlepsze trafia się innym."
],



blokady_energii: [
 "Czerwona: (1) Bezpieczeństwo, Przetrwanie, Tożsamość.",
 "Pomarańczowa: (2) Związki, Pieniądze/ Seks, Twórcza inwencja.",
 "Żółta: (3) Pewność siebie, Lęk/ Zaufanie, Władza.",
 "Zielona: (4) Współczucie/ Przebaczenie, Miłość/ Nienawiść, Złość/ Żal.",
 "Błękitna: (5) Komunikacja, Krytycyzm, Wolna wola.",
 "Indygo: (6) Samoświadomość, Intuicja, Prawda.",
 "Fioletowa: (7) Duchowość, Natchnienie, Wiara."
],

nowa_opowiesc: [
 "NOWA OPOWIEŚĆ: 001. +Najgorsze już minęło.",
 "NOWA OPOWIEŚĆ: 002. +W przeszłości mi się udało, więc teraz też mi się uda.",
 "NOWA OPOWIEŚĆ: 003. Bardzo cieszy Mnie sposób, w jaki toczy się Moje życie.",
 "NOWA OPOWIEŚĆ: 004. Bóg obdarzył Mnie wieloma darami, którymi z radością dzielę się z innymi.",
 "NOWA OPOWIEŚĆ: 005. Gdy zachodzi potrzeba, dowiaduję się o wszystkim, co muszę wiedzieć.",
 "NOWA OPOWIEŚĆ: 006. Jestem absolutnie doskonały taki jaki jestem.",
 "NOWA OPOWIEŚĆ: 007. Jestem bardzo uzdolniony!",
 "NOWA OPOWIEŚĆ: 008. Jestem doskonały właśnie taki jaki jestem.",
 "NOWA OPOWIEŚĆ: 009. Jestem dostatecznie silny, by poradzić Sobie w życiu, ponieważ wierzę, że dam radę!",
 "NOWA OPOWIEŚĆ: 010. Jestem najważniejszą osobą w Moim życiu!",
 "NOWA OPOWIEŚĆ: 011. Jestem największym szczęściarzem na świecie; przepełnia Mnie wdzięczność.",
 "NOWA OPOWIEŚĆ: 012. Jestem równie popularny jak inni.",
 "NOWA OPOWIEŚĆ: 013. Jestem teraz zawsze zauważany i doceniany.",
 "NOWA OPOWIEŚĆ: 014. Jestem wart tego, by mieć wszystko, czego pragnę. I domagam się tego teraz!",
 "NOWA OPOWIEŚĆ: 015. Jestem zawsze uwzględniany we wszystkich ważnych dla Mnie kwestiach.",
 "NOWA OPOWIEŚĆ: 016. Kiedy pokazuję, jaki jestem naprawdę, wszyscy Mnie kochają.",
 "NOWA OPOWIEŚĆ: 017. Mam teraz wszystko, czego pragnę. Z łatwością urzeczywistniam marzenia.",
 "NOWA OPOWIEŚĆ: 018. Mam zawsze wszystkiego pod dostatkiem, a pieniądze napływają do Mnie teraz szerokim strumieniem.",
 "NOWA OPOWIEŚĆ: 019. Mogę odnieść sukces we wszystkim, na czym Mi zależy.",
 "NOWA OPOWIEŚĆ: 020. Mogę osiągnąć wszystko; a gdy czasem coś Mi nie wyjdzie, to nie szkodzi!",
 "NOWA OPOWIEŚĆ: 021. Moje życie funkcjonuje doskonale - rozpiera Mnie energia!",
 "NOWA OPOWIEŚĆ: 022. Moje życie to fascynująca przygoda.",
 "NOWA OPOWIEŚĆ: 023. Nie jestem swoim ciałem, ale kocham i akceptuję ciało, które posiadam.",
 "NOWA OPOWIEŚĆ: 024. Nigdy nie będę samotny, jeśli tak postanowię.",
 "NOWA OPOWIEŚĆ: 025. Nikt nie może Mi niczego narzucać - sam podejmuję swoje decyzje.",
 "NOWA OPOWIEŚĆ: 026. Wierzę, że zawsze mogę liczyć na siebie oraz na opiekę ze strony Wszechświata.",
 "NOWA OPOWIEŚĆ: 027. Wolno Mi być SOBĄ!",
 "NOWA OPOWIEŚĆ: 028. Wszyscy darzą Mnie szacunkiem.",
 "NOWA OPOWIEŚĆ: 029. Wszyscy kochają Mnie właśnie takim, jakim jestem.",
 "NOWA OPOWIEŚĆ: 030. Wszyscy Mnie lubią takiego jakim jestem.",
 "NOWA OPOWIEŚĆ: 031. Wszystkie aspekty Mojego życia pozostają w doskonałej równowadze.",
 "NOWA OPOWIEŚĆ: 032. Z łatwością odczuwam i wyrażam Swoje uczucia.", // Poprawiono na "Swoje" dla spójności
 "NOWA OPOWIEŚĆ: 033. Z przekonaniem wyrażam Swoje myśli, poglądy i uczucia.",
 "NOWA OPOWIEŚĆ: 034. Zajmuję się tym, na co mam wpływ, powierzając resztę spraw Sile Wyższej.",
 "NOWA OPOWIEŚĆ: 035. Zasługuję na wszystko, czego pragnę i domagam się tego teraz!",
 "NOWA OPOWIEŚĆ: 036. Życie jest teraz takie proste. Jadę na wakacje.",
 "NOWA OPOWIEŚĆ: 037. Żyję przepełniony mocą i poczuciem szczęścia.",
 "NOWA OPOWIEŚĆ: 038. Żyję w zgodzie ze sobą."
];

projekcje: ["⬆️", "↗️", "➡️", "↘️", "⬇️", "↙️", "⬅️", "↖️"]
}
